#!/bin/sh
#
# Adds aliases to the system.
#

PKG=${PKG-`dirname ${0}`}
source "${PKG}/shared/log.inc"
source "${PKG}/shared/util.inc"


linfo "Adding aliases to the system"
ensure_line_in_file "/etc/profiles" "alias ll='ls -la --group-directories-first'"
