#!/bin/sh
#
# Configure general system options.
#

PKG=${PKG-`dirname ${0}`}
source "${PKG}/shared/command.inc"
source "${PKG}/shared/config.inc"
source "${PKG}/shared/log.inc"


linfo "Configuring global SysLog IP"
run uci set "system.@system[0].log_ip=${TARGET_SYSLOG_IP}"
run uci commit

