#!/bin/sh
#
# Configures USB extroot.
# Requires USB packages and a USB device connected.
# USB packages are installed by install-boot-packages.
#

PKG=${PKG-`dirname ${0}`}
source "${PKG}/shared/command.inc"
source "${PKG}/shared/config.inc"
source "${PKG}/shared/log.inc"
source "${PKG}/shared/uci.inc"


# Check device to use.
if [ -z "${USB_ROOT_DEV}" ]; then
  # Attempt to detect the partition automagically.
  devs_count=$(ls /dev/ | egrep "sd.[0-9]" | wc -l)

  if [ 0 -eq "${devs_count}" ]; then
    lerror "Unable to detect any partition matching '/dev/sd.[0-9]'."
    lerror "You can specify the partition by running " \
        "USB_ROOT_DEV=\"/dev/sda1\" <command>"
    exit 1
  fi

  if [ "${devs_count}" -gt 1 ]; then
    lerror "Too many partition matching '/dev/sd.[0-9]'."
    lerror "You can specify the partition by running " \
        "USB_ROOT_DEV=\"/dev/sda1\" <command>"
    exit 2
  fi

  USB_ROOT_DEV="/dev/$(ls /dev/ | egrep "sd.[0-9]")"

else
  [ -b "${USB_ROOT_DEV}" ] || (
    lerror "Specified device '${USB_ROOT_DEV}' is not a valid block device.";
    exit 3
  )
fi


lwarn "Using partition '${USB_ROOT_DEV}'. Process will resume in 2 seconds."
run sleep 2

# Find out if partition is mounted.
mount_location=$(mount | grep "${USB_ROOT_DEV}" | awk '{print $3}')

# If not mount it.
if [ -z "${mount_location}" ]; then
  run mount "${USB_ROOT_DEV}" "${USB_MOUNT_POINT}"
  mount_location="${USB_MOUNT_POINT}"
fi


# Setup fstab file.
# Add /overlay target.
# Add /overlay-boot target.
partition_uuid=$(block detect | grep uuid | awk '{print $3}' | cut -d\' -f2)
linfo "Detected partiotion uuid '${partition_uuid}'. Resuming in 2 secs."
run sleep 2


linfo "Setting global fstab options"
ensure_unamed_section "fstab" "global"
run uci set "fstab.@global[0].anon_mount=0"
run uci set "fstab.@global[0].anon_swap=0"
run uci set "fstab.@global[0].auto_mount=1"
run uci set "fstab.@global[0].auto_swap=1"
run uci set "fstab.@global[0].check_fs=0"
run uci set "fstab.@global[0].delay_root=5"

linfo "Configuring overlay mount point"
ensure_named_section "fstab.overlay" "mount"
run uci set "fstab.overlay.enabled=1"
run uci set "fstab.overlay.fstype=ext4"
run uci set "fstab.overlay.target=/overlay"
run uci set "fstab.overlay.uuid=${partition_uuid}"

linfo "Configuring overlay-boot mount point"
ensure_named_section "fstab.overlay_boot" "mount"
run uci set "fstab.overlay_boot.device=/dev/mtdblock3"
run uci set "fstab.overlay_boot.enabled=1"
run uci set "fstab.overlay_boot.enabled_fsck=0"
run uci set "fstab.overlay_boot.fstype=jffs2"
run uci set "fstab.overlay_boot.options=rw,sync"
run uci set "fstab.overlay_boot.target=/overlay-boot"
if [ ! -d "/overlay-boot" ]; then
  run mkdir "/overlay-boot"
fi


linfo "Committing *ALL* changes"
run uci commit


# Enable fstab at boot.
linfo "Enable fstab at boot"
/etc/init.d/fstab enable


# Copy data over to overlay partition.
linfo "Copying data to USB partition"
run tar -C /overlay -cvf - . | tar -C "${mount_location}" -xf -
