#!/bin/sh
#
# Configures wireless devices and networks.
#

PKG=${PKG-`dirname ${0}`}
source "${PKG}/shared/command.inc"
source "${PKG}/shared/config.inc"
source "${PKG}/shared/log.inc"
source "${PKG}/shared/uci.inc"
source "${PKG}/priv/passwords.inc"


# Configure radio devices.
linfo "Configuring wireless devices"
run uci set wireless.radio0.country=GB
run uci set wireless.radio1.country=GB

# Delete all default wifi interfaces.
uci_delete_anon_sections "wireless" "wifi-iface"

# Create new WiFi network (if not there yet).
if [ 1 -eq "$(uci show wireless.lan > /dev/null 2>&1; echo $?)" ]; then
  linfo "Creating LAN wireless section"
  run uci set "wireless.lan=wifi-iface"
fi

# Configure named wifi network.
linfo "Configuring LAN wireless"
run uci set "wireless.lan.device=radio0"
run uci set "wireless.lan.encryption=psk2"
run uci set "wireless.lan.key=${LAN_WIFI_PASSWORD}"
run uci set "wireless.lan.mode=ap"
run uci set "wireless.lan.network=lan"
run uci set "wireless.lan.ssid=${LAN_WIFI_NAME}"

linfo "Commiting wireless changes"
run uci commit

